// <auto-generated />
using System;
using EagleConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EagleConnect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109230919_AddRequestedByIdToConnection")]
    partial class AddRequestedByIdToConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EagleConnect.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("/images/default-avatar.svg");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EagleConnect.Models.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("User1Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("User2Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Connections", t =>
                        {
                            t.HasCheckConstraint("CK_Connection_DifferentUsers", "User1Id != User2Id");
                        });
                });

            modelBuilder.Entity("EagleConnect.Models.ConnectionPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PosterId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Seeking")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PosterId");

                    b.ToTable("ConnectionPosts");
                });

            modelBuilder.Entity("EagleConnect.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EagleConnect.Models.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MenteeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MentorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.ToTable("Relationships", t =>
                        {
                            t.HasCheckConstraint("CK_Relationship_DifferentUsers", "MentorId != MenteeId");
                        });
                });

            modelBuilder.Entity("EagleConnect.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7698),
                            Description = "Core computer science knowledge",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7707),
                            Description = "Business management and administration",
                            Name = "Business Administration"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7709),
                            Description = "Healthcare and patient care",
                            Name = "Nursing"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7711),
                            Description = "Engineering principles and practices",
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7784),
                            Description = "Human behavior and mental health",
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7789),
                            Description = "Financial accounting and bookkeeping",
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7793),
                            Description = "Marketing strategies and techniques",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7794),
                            Description = "Financial management and analysis",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 9,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7796),
                            Description = "Mathematical concepts and problem solving",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7798),
                            Description = "Biological sciences and research",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7800),
                            Description = "C# programming language",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7801),
                            Description = "JavaScript programming language",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 13,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7803),
                            Description = "Python programming language",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7804),
                            Description = "Microsoft Azure cloud platform",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7806),
                            Description = "AI and machine learning techniques",
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 16,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7807),
                            Description = "Data analysis and visualization",
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7808),
                            Description = "Frontend and backend web development",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 18,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7811),
                            Description = "Database design and management",
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = 19,
                            Category = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7812),
                            Description = "Leading teams and projects",
                            Name = "Leadership"
                        },
                        new
                        {
                            Id = 20,
                            Category = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7814),
                            Description = "Effective communication skills",
                            Name = "Communication"
                        },
                        new
                        {
                            Id = 21,
                            Category = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7815),
                            Description = "Analytical and creative problem solving",
                            Name = "Problem Solving"
                        },
                        new
                        {
                            Id = 22,
                            Category = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7816),
                            Description = "Collaborative work and team building",
                            Name = "Teamwork"
                        },
                        new
                        {
                            Id = 23,
                            Category = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7818),
                            Description = "Efficient time and task management",
                            Name = "Time Management"
                        },
                        new
                        {
                            Id = 24,
                            Category = 2,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7819),
                            Description = "Analytical and critical thinking",
                            Name = "Critical Thinking"
                        },
                        new
                        {
                            Id = 25,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7821),
                            Description = "Managing projects and resources",
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 26,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7822),
                            Description = "Professional networking and relationship building",
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 27,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7824),
                            Description = "Guiding and developing others",
                            Name = "Mentoring"
                        },
                        new
                        {
                            Id = 28,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7825),
                            Description = "Career planning and advancement",
                            Name = "Career Development"
                        },
                        new
                        {
                            Id = 29,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7826),
                            Description = "Research methods and analysis",
                            Name = "Research"
                        },
                        new
                        {
                            Id = 30,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 11, 9, 23, 9, 18, 420, DateTimeKind.Utc).AddTicks(7828),
                            Description = "Educational instruction and training",
                            Name = "Teaching"
                        });
                });

            modelBuilder.Entity("EagleConnect.Models.StudentOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MeetingSchedule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("StudentOrganizations");
                });

            modelBuilder.Entity("EagleConnect.Models.StudentOrganizationMember", b =>
                {
                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentOrganizationMembers");
                });

            modelBuilder.Entity("EagleConnect.Models.UserSkill", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EagleConnect.Models.Connection", b =>
                {
                    b.HasOne("EagleConnect.Models.ApplicationUser", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EagleConnect.Models.ApplicationUser", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EagleConnect.Models.ApplicationUser", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedBy");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("EagleConnect.Models.ConnectionPost", b =>
                {
                    b.HasOne("EagleConnect.Models.ApplicationUser", "Poster")
                        .WithMany("ConnectionPosts")
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("EagleConnect.Models.Message", b =>
                {
                    b.HasOne("EagleConnect.Models.Connection", "Connection")
                        .WithMany("Messages")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EagleConnect.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Connection");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("EagleConnect.Models.Relationship", b =>
                {
                    b.HasOne("EagleConnect.Models.ApplicationUser", "Mentee")
                        .WithMany("MenteeRelationships")
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EagleConnect.Models.ApplicationUser", "Mentor")
                        .WithMany("MentorRelationships")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("EagleConnect.Models.StudentOrganizationMember", b =>
                {
                    b.HasOne("EagleConnect.Models.StudentOrganization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EagleConnect.Models.ApplicationUser", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EagleConnect.Models.UserSkill", b =>
                {
                    b.HasOne("EagleConnect.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EagleConnect.Models.ApplicationUser", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EagleConnect.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EagleConnect.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EagleConnect.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EagleConnect.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EagleConnect.Models.ApplicationUser", b =>
                {
                    b.Navigation("ConnectionPosts");

                    b.Navigation("MenteeRelationships");

                    b.Navigation("MentorRelationships");

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EagleConnect.Models.Connection", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EagleConnect.Models.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EagleConnect.Models.StudentOrganization", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
